language: r
sudo: false
cache: packages
warnings_are_errors: false

env:
- RGL_USE_NULL=TRUE

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

before_install:
  - tlmgr install index
  - sudo apt-get -y install  libglu1-mesa-dev

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

notifications:
  email:
    recipients:
      - bonhomme.vincent@gmail.com
    on_success: change
    on_failure: change

